# Generated by Django 5.2.6 on 2026-06-27 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('report_file', models.FileField(upload_to='health_reports/%Y/%m/')),
                ('report_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Health Report',
                'verbose_name_plural': 'Health Reports',
                'db_table': 'health_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Once Daily'), ('TWICE', 'Twice Daily'), ('THRICE', 'Thrice Daily'), ('WEEKLY', 'Weekly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(help_text='Primary reminder time')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medication Reminder',
                'verbose_name_plural': 'Medication Reminders',
                'db_table': 'medication_reminders',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WoundCareLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wound_care/%Y/%m/')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], max_length=10)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wound Care Log',
                'verbose_name_plural': 'Wound Care Logs',
                'db_table': 'wound_care_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, help_text='mg/dL', max_digits=6, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Fahrenheit', max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=1, help_text='SpO2 %', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
